name: Build with Maven

on:
  push:
    branches: [ main ]  # Change "main" to your main branch name if different
  pull_request:  # Optional: Trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Or another desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code from the repository

      - name: Set up JDK 17  # Change version if needed
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'  # Optionally cache Maven packages

      - name: Build with Maven
        run: mvn package -DskipTests  # Optionally add -DskipTests to skip tests

      # Uncomment these steps if you want to run tests:
      # - name: Run tests with Maven
      #   run: mvn test

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory and execute command
        run:
        cd TEST1/poc-soapui-project.xml
        mvn com.smartbear.soapui:soapui-maven-plugin:5.5.0:test

      - name: Change directory and execute command
        run: |
        cd TEST2/poc-soapui-project.xml
        mvn com.smartbear.soapui:soapui-maven-plugin:5.5.0:test

      - name: Change directory and execute command
        run: |
        cd TEST3/poc-soapui-project.xml
        mvn com.smartbear.soapui:soapui-maven-plugin:5.5.0:test

      - name: Change directory and execute command
        run: |
        cd TEST4/poc-soapui-project.xml
        mvn com.smartbear.soapui:soapui-maven-plugin:5.5.0:test

      - name: Change directory and execute command
        run: |
        cd TEST5/poc-soapui-project.xml
        mvn com.smartbear.soapui:soapui-maven-plugin:5.5.0:test

      - name: Change directory and execute command
        run: |
        cd TEST6/poc-soapui-project.xml
        mvn com.smartbear.soapui:soapui-maven-plugin:5.5.0:test